language: c++
before_install:
  - sudo apt-add-repository ppa:nelhage/livegrep
  - sudo apt-get update
  - sudo apt-get install libgflags-dev libjson0-dev libboost-system-dev libboost-filesystem-dev
script: make test
