language: c++
addons:
  apt:
    packages:
    - libjson0-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libsparsehash-dev
sudo: false
before_install:
  - bash travis.sh
cache:
  directories:
    - deps
script:
  - env -u GOPATH make all test gflags=$(pwd)/deps/gflags/build libgit2=$(pwd)/deps/libgit2/build
  - env GOPATH=$(pwd)/.gopath go test github.com/livegrep/livegrep/client/test -test.repo $(pwd)/deps/linux
compiler:
  - gcc
