language: c++
addons:
  apt:
    packages:
    - libjson0-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libsparsehash-dev
  artifacts:
    paths:
      - builds
    bucket: livegrep
    target_paths: builds
    s3_region: us-west-2
sudo: false
before_install:
  - bash travis.sh
cache:
  directories:
    - deps
script:
  - env -u GOPATH make all test gflags=$(pwd)/deps/gflags/build libgit2=$(pwd)/deps/libgit2/build
  - env GOPATH=$(pwd)/.gopath go test github.com/livegrep/livegrep/client/test -test.repo $(pwd)/deps/linux
compiler:
  - gcc
after_success: |
  mkdir -p builds
  rev=$(git rev-parse HEAD | head -c10)
  builddir="livegrep-$rev"
  tar --xform s,^,"$builddir/",S -czf "builds/$builddir.tgz" bin web doc README.md COPYING
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIAQXOJA3S2ZTGLWA
    - secure: "YK0pGNgQ4Xf+Rcy6cC8Mg14WI5RYZLIbnWRDMG/FUUqF4eS3RSiez8zxEgxMVtp5eYeG77jFRNdTIZA5UwlEr+Bvl9Q12d12ba5t5kVtB1UEuouIH8p4oDp6mNiuWVqkmlOA4IG4Ao6/n78QMuGCZuxaZ+9lMO/wA1vDt9woCJ8="
