language: c++
before_install:
- sudo apt-add-repository -y ppa:nelhage/livegrep
- sudo apt-get -qq update
- sudo apt-get -y install libgflags-dev libgit2-dev libjson0-dev libboost-system-dev
  libboost-filesystem-dev libsparsehash-dev
- test -d linux || git clone --depth=1 --branch v3.17 https://github.com/torvalds/linux linux
cache:
  directories:
    - linux
script:
  - env -u GOPATH make all test
  - env GOPATH=$(pwd)/.gopath go test github.com/livegrep/livegrep/client/test -test.repo $(pwd)/linux
compiler:
- gcc
cache: apt
